require_relative 'linguist-ext/get-dir'
require_relative 'linguist-ext/helper'
require_relative 'linguist-ext/summary'
require_relative 'linguist-ext/tally'
require_relative 'linguist-ext/git'
require_relative 'linguist-ext/describe'
